server:
  port: 7777

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8088/realms/ecommerce"
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
              - Path=/ms-client/* *
          filters:
              - RewritePath=/ms-client/(?<s>.*), /${s}
          uri: lb://ms-client

